version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
